version: '2.1'
services:
  pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432
    
  ns:
    build: ./others
    environment:
      - DB_URL=jdbc:postgresql://pg:5432/db
      - DB_USER=postgres
      - DB_PASS=admin
    ports:
      - 8080:8080
    depends_on:
      pg:
        condition: service_healthy
    

volumes:
  data: