version: '3'
services:
  pgns:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - datans:/var/lib/postgresql/data
    
  ns:
    build: ./others
    environment:
      - DB_URL=jdbc:postgresql://pgns:5432/db
    ports:
      - 8021:8080
    depends_on:
      pgns:
        condition: service_healthy

  pgbg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - databg:/var/lib/postgresql/data
    
  bg:
    build: ./others
    environment:
      - DB_URL=jdbc:postgresql://pgbg:5432/db
    ports:
      - 8011:8080
    depends_on:
      pgbg:
        condition: service_healthy

  pgnis:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - datanis:/var/lib/postgresql/data
    
  nis:
    build: ./others
    environment:
      - DB_URL=jdbc:postgresql://pgnis:5432/db
    ports:
      - 8018:8080
    depends_on:
      pgnis:
        condition: service_healthy

  pgcentral:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - datacentral:/var/lib/postgresql/data
    
  central:
    build: ./central
    environment:
      - DB_URL=jdbc:postgresql://pgcentral:5432/db
    ports:
      - 8000:8080
    depends_on:
      pgcentral:
        condition: service_healthy

enviroment:
  - DB_USER=postgres
  - DB_PASS=admin
  - CENTRAL_URL=http://central:8000
volumes:
  datans:
  databg:
  datanis: